data_dir: "data"
output_dir: "output/experiments"

# preprocessing hyperparameters
preprocessing:
  window_size: 128
  stride: 64
  min_sequence_length: 20
  padding_value: 0.0
  sampling_rate: 50.0
  fft_bands:
    - [0.5, 2]
    - [2, 5]
    - [5, 10]
    - [10, 20]
  wavelet: "db4"
  wavelet_level: 3
  tda_dimension: 1
  tda_bins: 20
  tda_sigma: 0.1
  tof_depth: 5
  tof_height: 8
  tof_width: 8


sensor_cols:
  - acc_x
  - acc_y
  - acc_z
  - rot_w
  - rot_x
  - rot_y
  - rot_z


demographics_cols:
  - adult_child
  - age
  - sex
  - handedness
  - height_cm
  - shoulder_to_wrist_cm
  - elbow_to_wrist_cm