data_dir: "data"
output_dir: "output/experiments"

# preprocessing hyperparameters
preprocessing:
  window_size: 256
  stride: 128
  sampling_rate: 50.0
  fft_bands:
    - [0.5, 2]
    - [2, 5]
    - [5, 10]
    - [10, 20]
  wavelet: "db4"
  wavelet_level: 3
  tda_dimension: 1
  tda_bins: 20
  tda_sigma: 0.1
