experiment_name: "baseline_lightgbm_v1"
output_dir: "experiments"
save_model: true
save_predictions: true
save_feature_importance: true
save_confusion_matrix: true

model:
  model_type: "lightgbm"
  objective: "multiclass"
  num_class: 3
  random_state: 42
  n_estimators: 100
  learning_rate: 0.1
  max_depth: 6
  min_child_samples: 20
  subsample: 0.8
  colsample_bytree: 0.8
  reg_alpha: 0.0
  reg_lambda: 0.0
  class_weight: null
  device: "cpu"

data:
  data_dir: "data"
  train_file: "train.csv"
  test_file: "test.csv"
  target_column: "target"
  feature_columns: null  # nullの場合は自動選択
  test_size: 0.2
  random_state: 42
  preprocessing: null

training:
  cv_folds: 5
  cv_strategy: "stratified"
  group_column: null
  scoring: "f1_macro"
  n_jobs: -1
  verbose: 1
  early_stopping_rounds: 50
  eval_metric: "multi_logloss"
